--- 
title: "STAT 3080: From Data to Knowledge"
author: "Jeffrey Woo"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "Course Notes for STAT 3080"
---

# Preface {-}

## Course Overview and Goals {-}

This course focuses on a simulation-based inference approach to concepts taught in elementary statistics. It focuses on using simulations to investigate the operating characteristics of common inferential procedures in statistics, so you can make practical decisions on when to use these procedures to learn about the data at hand. 

For example, you may have heard that a hypothesis test for the mean from one sample assumes the data come from a normal distribution, or that the sample size is “large enough”. You may have wondered what constitutes being “large enough”, and you may have learned or read that a sample size of 25 or 30 will be considered “large enough”. The true answer is actually “it depends”, as various other factors play a role.

You will learn to design and run simulations to develop a more nuanced understanding of how reliable these inferential procedures are when the assumptions they are based on are not met. It turns out that there are mathematical proofs that can answer such questions, but they are usually fairly complicated, so we will use simulations in place of these mathematical proofs. 

In order to design such simulations, a fair amount of knowledge with coding using R will be needed, which you will learn in the first portion of this course. This course is not a programming course; it is simulation-based inference using R. 

Upon successful completion of this course, you will be able to:

1. Use simulation to study operating characteristics of statistical methodologies.
2. Understand and apply appropriate statistical methodologies under various data scenarios.
3. Use simulation to estimate statistical quantities which are difficult to compute.
4. Use simulation to assess the quality of statistical estimators. 
5. Communicate results from simulations in writing, based on principles of reproducible research. 

## Background Needed for the Course {-}

The official prerequisites are:

1. Intro statistics (One of STAT 1100, STAT 1120, STAT 2020, STAT 2120, STAT 3120, APMA 3110, APMA 3120).
2. Intro programming (One of STAT 1601, STAT 1602, STAT 3250, CS 1110, CS 1111, CS 1112, CS 1113).

The course is presented assuming you are familiar with inferential procedures associated with one- or two-sample means and proportions, as well as basic programming skills. The course will not cover these. 

## Required Software {-}

The software introduced and featured in this course is R. RStudio is a software that runs R with additional user-friendly features. RStudio will be used for all in-class R demonstrations. Both R and RStudio are free for download.

- R will need to be [downloaded first](https://www.r-project.org/). 
- Then [downloaded RStudio](https://docs.posit.co/ide/user/#rstudio-ide-oss-downloads).

You are **highly encouraged** to use R Markdown to create PDF documents for homeworks and the project, which uses a type-setting platform called LaTeX. LaTeX can be installed by running the following two commands in the R Console:

```{r, eval=FALSE}
install.packages("tinytex")
tinytex::install_tinytex()
```

## Chapters {-}

The chapters for the book is as follows:

- Chapters ??? focus on core R skills needed: .
- Chapters ??? focus on

## Reporting Issues with Course Notes {-}

If you find any issues (typos, formatting, etc), please report them at [my GitHub page](https://github.com/jwooSDS/stat3080/issues). Please be as specific as you can, by specifying the section and paragraph where the issue is found.

Serious issues that need my immediate attention should be posted on our Canvas page on Piazza or emailed to me. 





