<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 13 The Bootstrap | STAT 3080: From Data to Knowledge</title>
<meta name="author" content="Jeffrey Woo">
<meta name="description" content="13.1 Introduction In Section 12, we learned about confidence intervals for the mean, the proportion, the difference in two independent means, and the difference in two independent proportions....">
<meta name="generator" content="bookdown 0.34 with bs4_book()">
<meta property="og:title" content="Chapter 13 The Bootstrap | STAT 3080: From Data to Knowledge">
<meta property="og:type" content="book">
<meta property="og:description" content="13.1 Introduction In Section 12, we learned about confidence intervals for the mean, the proportion, the difference in two independent means, and the difference in two independent proportions....">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 13 The Bootstrap | STAT 3080: From Data to Knowledge">
<meta name="twitter:description" content="13.1 Introduction In Section 12, we learned about confidence intervals for the mean, the proportion, the difference in two independent means, and the difference in two independent proportions....">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.4.2/transition.js"></script><script src="libs/bs3compat-0.4.2/tabs.js"></script><script src="libs/bs3compat-0.4.2/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">STAT 3080: From Data to Knowledge</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Preface</a></li>
<li><a class="" href="Rbasics.html"><span class="header-section-number">1</span> R Basics</a></li>
<li><a class="" href="rmd.html"><span class="header-section-number">2</span> R Markdown</a></li>
<li><a class="" href="subset.html"><span class="header-section-number">3</span> Working with Data Structures</a></li>
<li><a class="" href="func.html"><span class="header-section-number">4</span> Functions</a></li>
<li><a class="" href="control.html"><span class="header-section-number">5</span> Control Flow</a></li>
<li><a class="" href="sims.html"><span class="header-section-number">6</span> Simulations</a></li>
<li><a class="" href="applyfam.html"><span class="header-section-number">7</span> Apply Family</a></li>
<li><a class="" href="ggplot.html"><span class="header-section-number">8</span> Data Visualizations (ggplot2)</a></li>
<li><a class="" href="dplyr.html"><span class="header-section-number">9</span> Data Wrangling (dplyr)</a></li>
<li><a class="" href="EDA.html"><span class="header-section-number">10</span> Exploratory Data Analysis and Tidying Data</a></li>
<li><a class="" href="clt.html"><span class="header-section-number">11</span> Sampling Distributions and the Central Limit Theorem</a></li>
<li><a class="" href="CI.html"><span class="header-section-number">12</span> Confidence Intervals</a></li>
<li><a class="active" href="boot.html"><span class="header-section-number">13</span> The Bootstrap</a></li>
<li><a class="" href="hyp.html"><span class="header-section-number">14</span> Hypothesis Testing for Means</a></li>
<li><a class="" href="prac.html"><span class="header-section-number">15</span> Practical Considerations with Hypothesis Testing</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="boot" class="section level1" number="13">
<h1>
<span class="header-section-number">13</span> The Bootstrap<a class="anchor" aria-label="anchor" href="#boot"><i class="fas fa-link"></i></a>
</h1>
<div id="introduction-3" class="section level2" number="13.1">
<h2>
<span class="header-section-number">13.1</span> Introduction<a class="anchor" aria-label="anchor" href="#introduction-3"><i class="fas fa-link"></i></a>
</h2>
<p>In Section <a href="CI.html#CI">12</a>, we learned about confidence intervals for</p>
<ul>
<li>the mean,</li>
<li>the proportion,</li>
<li>the difference in two independent means, and</li>
<li>the difference in two independent proportions.</li>
</ul>
<p>These intervals are based on their known sampling distributions, which usually require some conditions to be met. Confidence intervals for any other parameter that are based on known sampling distributions work similarly. We work out the confidence interval of an estimator by using the framework in equation <a href="CI.html#eq:8-CIbasic2">(12.2)</a>: we add and subtract the margin of error to and from the point estimate. The margin of error is the critical value multiplied by the standard error of the estimator. The critical value is based on the sampling distribution of the estimator. This framework requires us to know the sampling distribution and the standard error of the estimator.</p>
<p>This naturally leads to a question: what if the conditions for these sampling distributions are not met, or if the estimator we are working on has no known sampling distribution? In this section, we will learn about the bootstrap, which is used when the sampling distribution of an estimator is unknown.</p>
</div>
<div id="bootstrap" class="section level2" number="13.2">
<h2>
<span class="header-section-number">13.2</span> The Bootstrap<a class="anchor" aria-label="anchor" href="#bootstrap"><i class="fas fa-link"></i></a>
</h2>
<p>There are estimators whose sampling distributions are unknown, for example, the sample median. How can we construct confidence intervals for the median?</p>
<p>One idea could be to collect many random samples, compute the sample median from each sample, and create a density plot like we did in Monte Carlo simulations in Figures <a href="clt.html#fig:dist-samp-mean">11.2</a>, <a href="clt.html#fig:dist-U">11.3</a>, and <a href="clt.html#fig:dist-E">11.4</a>. However, this is not feasible in real life as we rarely have the time and money to go around obtaining many random samples. We are only able to work with the one random sample that we have.</p>
<p>A method to work around these issues is the <strong>bootstrap</strong>. The bootstrap will enable us to:</p>
<ul>
<li><p>Estimate the standard error and variance of estimators if there are no known formulas for them.</p></li>
<li><p>Construct confidence intervals for estimators with unknown sampling distributions and unknown formulas for their standard errors.</p></li>
</ul>
<p>We can do these without having to collect data from many random samples. Before going into how the bootstrap works, we remind ourselves of how Monte Carlo simulations work in terms of finding the sampling distribution and standard errors of estimators.</p>
<div id="estimating-sampling-distributions-using-many-random-samples" class="section level3" number="13.2.1">
<h3>
<span class="header-section-number">13.2.1</span> Estimating Sampling Distributions Using Many Random Samples<a class="anchor" aria-label="anchor" href="#estimating-sampling-distributions-using-many-random-samples"><i class="fas fa-link"></i></a>
</h3>
<p>When using Monte Carlo simulations to estimate the sampling distribution of estimators (see the code that generated Figures <a href="clt.html#fig:dist-samp-mean">11.2</a>, <a href="clt.html#fig:dist-U">11.3</a>, and <a href="clt.html#fig:dist-E">11.4</a> as examples), we typically did the following:</p>
<ol style="list-style-type: decimal">
<li><p>Assume the data follow some known distribution with PDF <span class="math inline">\(f_X\)</span>.</p></li>
<li><p>Simulate <span class="math inline">\(n\)</span> data points from this assumed distribution <span class="math inline">\(K\)</span> times, with <span class="math inline">\(K\)</span> being large, to obtain <span class="math inline">\(K\)</span> replicate datasets of size <span class="math inline">\(n\)</span> denoted by <span class="math inline">\(\mathcal{X}^{1}, \cdots, \mathcal{X}^{K}\)</span>.</p></li>
<li><p>For each dataset, calculate the value of the estimator <span class="math inline">\(\hat{\Theta}\)</span>. Since we have <span class="math inline">\(K\)</span> datasets, we will have <span class="math inline">\(K\)</span> values for the estimators, denoted by <span class="math inline">\(\hat{\Theta}^{1}, \cdots, \hat{\Theta}^{K}\)</span>.</p></li>
<li><p>We estimate the true mean of <span class="math inline">\(\hat{\Theta}\)</span> by taking the sample mean of <span class="math inline">\(\hat{\Theta}^{1}, \cdots, \hat{\Theta}^{K}\)</span>.</p></li>
<li><p>We estimate the true variance of <span class="math inline">\(\hat{\Theta}\)</span> by taking the sample variance of <span class="math inline">\(\hat{\Theta}^{1}, \cdots, \hat{\Theta}^{K}\)</span>. Square-rooting this value gives an estimate for the standard error of <span class="math inline">\(\hat{\Theta}\)</span>.</p></li>
<li><p>We create a density plot of <span class="math inline">\(\hat{\Theta}^{1}, \cdots, \hat{\Theta}^{K}\)</span> to estimate the sampling distribution of <span class="math inline">\(\hat{\Theta}\)</span>.</p></li>
</ol>
<p>As written earlier, the problem with applying this idea to an estimator that has an unknown sampling distribution is that we do not know its associated PDF <span class="math inline">\(f_X\)</span>. So we cannot carry out the steps listed. What the bootstrap does is to mimic these steps, when we only have access to data from one random sample. Next, we describe the steps that are carried out in the bootstrap. Pay attention to the similarities and differences in these steps with the steps above.</p>
</div>
<div id="the-bootstrap-algorithm" class="section level3" number="13.2.2">
<h3>
<span class="header-section-number">13.2.2</span> The Bootstrap Algorithm<a class="anchor" aria-label="anchor" href="#the-bootstrap-algorithm"><i class="fas fa-link"></i></a>
</h3>
<p>Instead of simulating <span class="math inline">\(K\)</span> replicate datasets from an assumed distribution, we simulate <span class="math inline">\(K\)</span> replicate datasets by sampling, <strong>with replacement</strong>, <span class="math inline">\(n\)</span> data points from the original dataset. The “with replacement” term is key: it means that when a data point is sampled, it is returned to the original dataset and it can be sampled again.</p>
<p>Let <span class="math inline">\(\mathcal{X}\)</span> denote the original dataset with <span class="math inline">\(n\)</span> observations. Let <span class="math inline">\(\hat{\theta}\)</span> denote the value of the estimator from the original dataset.</p>
<ol style="list-style-type: decimal">
<li><p>Synthesize <span class="math inline">\(K\)</span> bootstrapped datasets <span class="math inline">\(\mathcal{Y}^{(1)}, \cdots, \mathcal{Y}^{(K)}\)</span> where each bootstrapped dataset is derived by sampling <span class="math inline">\(n\)</span> data points from the original dataset, with replacement.</p></li>
<li><p>For each dataset, calculate the value of the estimator <span class="math inline">\(\hat{\Theta}\)</span>. Since we have <span class="math inline">\(K\)</span> bootstrapped datasets, we will have <span class="math inline">\(K\)</span> values for the estimators, denoted by <span class="math inline">\(\hat{\Theta}^{(1)}, \cdots, \hat{\Theta}^{(K)}\)</span>.</p></li>
<li><p>We estimate the expected value of <span class="math inline">\(\hat{\Theta}\)</span> by taking the sample mean of <span class="math inline">\(\hat{\Theta}^{(1)}, \cdots, \hat{\Theta}^{(K)}\)</span>. This value is denoted by <span class="math inline">\(M_b(\hat{\Theta})\)</span>.</p></li>
<li><p>We estimate the true variance of <span class="math inline">\(\hat{\Theta}\)</span> by taking the sample variance of <span class="math inline">\(\hat{\Theta}^{(1)}, \cdots, \hat{\Theta}^{(K)}\)</span>. This value is denoted by <span class="math inline">\(V_b(\hat{\Theta})\)</span>, which we call the bootstrap variance of the estimator. Square-rooting <span class="math inline">\(V_b(\hat{\Theta})\)</span> gives an estimate for the standard error of <span class="math inline">\(\hat{\Theta}\)</span>, denoted by <span class="math inline">\(SE_b(\Theta)\)</span>. If <span class="math inline">\(K\)</span> is large enough, <span class="math inline">\(V_b(\hat{\Theta})\)</span> will approximate the true variance of the estimator.</p></li>
<li><p>We can create a density plot of <span class="math inline">\(\hat{\Theta}^{(1)}, \cdots, \hat{\Theta}^{(K)}\)</span> to estimate the sampling distribution of <span class="math inline">\(\hat{\Theta}\)</span>. If <span class="math inline">\(K\)</span> is large enough, this density plot will approximate the true PDF <span class="math inline">\(f_X\)</span> well.</p></li>
</ol>
<p>Comparing this algorithm with Monte Carlo simulations, the main differences are:</p>
<ul>
<li><p>With the bootstrap, we do not assume any distribution for the original data. With Monte Carlo simulations, we do make an assumption on the distribution for the original data.</p></li>
<li><p>The <span class="math inline">\(K\)</span> datasets are produced slightly differently. For the bootstrap, they are synthesized by sampling with replacement <span class="math inline">\(n\)</span> data points from the original dataset of size <span class="math inline">\(n\)</span>. With Monte Carlo simulations, we draw <span class="math inline">\(n\)</span> data points from its assumed distribution.</p></li>
</ul>
<p>The math that proves the bootstrap works is beyond the level of this class, although it is freely available online.</p>
<p>The bootstrap tends to work better as the number of bootstrap datasets ,<span class="math inline">\(K\)</span>, increases and as the sample size, <span class="math inline">\(n\)</span>, increases.</p>
</div>
<div id="confidence-intervals-using-the-bootstrap" class="section level3" number="13.2.3">
<h3>
<span class="header-section-number">13.2.3</span> Confidence Intervals using the Bootstrap<a class="anchor" aria-label="anchor" href="#confidence-intervals-using-the-bootstrap"><i class="fas fa-link"></i></a>
</h3>
<p>The <strong>basic</strong> (or reverse percentile ) bootstrap <span class="math inline">\((1-\alpha) \times 100\%\)</span> confidence interval for <span class="math inline">\(\theta\)</span> is</p>
<p><span class="math display" id="eq:8-CIboot">\[\begin{equation}
\left( \hat{\theta} - \hat{\delta}_{1-\alpha/2}^*, \hat{\theta} - \hat{\delta}_{\alpha/2}^* \right),
\tag{13.1}
\end{equation}\]</span></p>
<p>where <span class="math inline">\(\delta^* = (\hat{\Theta}^{(1)}, \cdots, \hat{\Theta}^{(K)}) - \hat{\theta}\)</span>, which is the difference between the estimator in the <span class="math inline">\(K\)</span> bootstrap samples and the value of the estimator in the original dataset, so <span class="math inline">\(\hat{\delta}_{\beta}^*\)</span> is the <span class="math inline">\(\beta \times 100\)</span>th percentile of <span class="math inline">\(\delta^*\)</span>.</p>
<p>You may notice that the confidence interval in equation <a href="boot.html#eq:8-CIboot">(13.1)</a> does not fit the general framework given in equation <a href="CI.html#eq:8-CIbasic2">(12.2)</a>. This is because the sampling distribution of the estimator may not be symmetric.</p>
<p>The math that derives this confidence interval is beyond the level of this class, although it is freely available online.</p>
<p>The bootstrap confidence interval tends to work better as <span class="math inline">\(K\)</span> increases and as <span class="math inline">\(n\)</span> increases.</p>
<p>Note: there are variations of the confidence interval based on the bootstrap. We will use the basic bootstrap confidence interval as specified in equation <a href="boot.html#eq:8-CIboot">(13.1)</a>.</p>
</div>
<div id="worked-example-2" class="section level3" number="13.2.4">
<h3>
<span class="header-section-number">13.2.4</span> Worked Example<a class="anchor" aria-label="anchor" href="#worked-example-2"><i class="fas fa-link"></i></a>
</h3>
<p>We have data on 400 credit card customers. A density plot of their credit limits is shown below:</p>
<div class="sourceCode" id="cb487"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://www.statlearning.com">ISLR2</a></span><span class="op">)</span></span>
<span><span class="va">Data</span><span class="op">&lt;-</span><span class="fu">ISLR2</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/pkg/ISLR2/man/Credit.html">Credit</a></span><span class="op">$</span><span class="va">Limit</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/density.html">density</a></span><span class="op">(</span><span class="va">Data</span><span class="op">)</span>, xlab<span class="op">=</span><span class="st">"Credit Limit"</span>, main<span class="op">=</span><span class="st">"Density Plot of Credit Limits"</span><span class="op">)</span></span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:8-credit"></span>
<img src="bookdown-demo_files/figure-html/8-credit-1.png" alt="Density Plot of Credit Limits" width="672"><p class="caption">
Figure 13.1: Density Plot of Credit Limits
</p>
</div>
<p>The density plot in Figure <a href="boot.html#fig:8-credit">13.1</a> informs us that the values of credit limits are skewed, so the median is a better measure of centrality for credit limits. We wish to estimate the population median credit limit, give a measure of uncertainty, as well as report a 95% confidence interval for the median credit limit. Since the sampling distribution of the sample median is unknown, we use the bootstrap:</p>
<div class="sourceCode" id="cb488"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">##actual sample median</span></span>
<span><span class="va">samp_median</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">Data</span><span class="op">)</span></span>
<span><span class="va">samp_median</span></span></code></pre></div>
<pre><code>## [1] 4622.5</code></pre>
<div class="sourceCode" id="cb490"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">K</span><span class="op">&lt;-</span><span class="fl">1000</span> <span class="co">##Number of bootstrap samples</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">77</span><span class="op">)</span></span>
<span></span>
<span><span class="co">##the sample function, with replace=TRUE, samples with replacement. </span></span>
<span><span class="co">##The replicate function repeats the sample function K times</span></span>
<span><span class="co">##if no size is specified in sample(), default is the length of the vector called Data</span></span>
<span><span class="va">boot.samples</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">replicate</a></span><span class="op">(</span><span class="va">K</span>,<span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="va">Data</span>, replace<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">##Each column in boot.samples represents each bootstrap sample</span></span>
<span></span>
<span><span class="co">##find the sample median of each column, since each column represents a bootstrap sample</span></span>
<span><span class="va">boot.medians</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">boot.samples</span>,<span class="fl">2</span>,<span class="va">median</span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="co">##bootstrap SE of the median is just the SD of the sample medians from each bootstrap sample</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">boot.medians</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 152.0525</code></pre>
<div class="sourceCode" id="cb492"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">##deltas</span></span>
<span><span class="va">boot_median_error</span> <span class="op">&lt;-</span> <span class="va">boot.medians</span><span class="op">-</span> <span class="va">samp_median</span></span>
<span></span>
<span><span class="co">##sort deltas</span></span>
<span><span class="va">boot_median_error_sort</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sort.html">sort</a></span><span class="op">(</span><span class="va">boot_median_error</span><span class="op">)</span></span>
<span></span>
<span><span class="co">##find CI based on equation</span></span>
<span><span class="va">alpha</span><span class="op">&lt;-</span><span class="fl">0.05</span></span>
<span><span class="va">p1</span> <span class="op">&lt;-</span> <span class="va">K</span><span class="op">*</span><span class="op">(</span><span class="va">alpha</span><span class="op">/</span><span class="fl">2</span><span class="op">)</span></span>
<span><span class="va">p2</span> <span class="op">&lt;-</span> <span class="va">K</span><span class="op">*</span><span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">alpha</span><span class="op">/</span><span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="va">samp_median</span> <span class="op">-</span> <span class="va">boot_median_error_sort</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">p2</span>,<span class="va">p1</span><span class="op">)</span><span class="op">]</span></span></code></pre></div>
<pre><code>## [1] 4380.0 4949.5</code></pre>
<p>We report the following:</p>
<ul>
<li>The sample median is $4622.5.</li>
<li>The standard error of the sample median is $152.0525.</li>
<li>The 95% confidence interval for the median credit limit is (4380.000, 4949.5). There is 95% probability that the true population median credit limit lies in the random interval between $4380 and $4949.50.</li>
</ul>
</div>
</div>
<div id="parametric-vs-non-parametric-methods" class="section level2" number="13.3">
<h2>
<span class="header-section-number">13.3</span> Parametric Vs Non-Parametric Methods<a class="anchor" aria-label="anchor" href="#parametric-vs-non-parametric-methods"><i class="fas fa-link"></i></a>
</h2>
<p>The confidence intervals from Section <a href="#CIs"><strong>??</strong></a> are based on the known sampling distributions of estimators, and have a closed form formula to calculate them. These confidence intervals are typically based on some conditions in order to be valid.</p>
<p>Such methods are sometimes called <strong>parametric methods</strong>, as the distributions they are based on fits a known probability distribution which can be specified by an equation via its PDF, <span class="math inline">\(f_X\)</span>.</p>
<p>The bootstrap, on the other hand, does not assume a known probability distribution. Therefore, the bootstrap is considered a <strong>non-parametric method</strong>, as the associated probability distribution is unknown and not associated with an equation like a PDF. Non-parametric methods tend to be more versatile, in the sense that they are based on less assumptions or conditions, and so can be applied in a wider variety of settings.</p>
<p>The only assumptions / conditions associated with the bootstrap are:</p>
<ul>
<li>The sample has to be representative of the population (similar to parametric methods).</li>
<li>The underlying population does not have very heavy tails.</li>
</ul>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="CI.html"><span class="header-section-number">12</span> Confidence Intervals</a></div>
<div class="next"><a href="hyp.html"><span class="header-section-number">14</span> Hypothesis Testing for Means</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#boot"><span class="header-section-number">13</span> The Bootstrap</a></li>
<li><a class="nav-link" href="#introduction-3"><span class="header-section-number">13.1</span> Introduction</a></li>
<li>
<a class="nav-link" href="#bootstrap"><span class="header-section-number">13.2</span> The Bootstrap</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#estimating-sampling-distributions-using-many-random-samples"><span class="header-section-number">13.2.1</span> Estimating Sampling Distributions Using Many Random Samples</a></li>
<li><a class="nav-link" href="#the-bootstrap-algorithm"><span class="header-section-number">13.2.2</span> The Bootstrap Algorithm</a></li>
<li><a class="nav-link" href="#confidence-intervals-using-the-bootstrap"><span class="header-section-number">13.2.3</span> Confidence Intervals using the Bootstrap</a></li>
<li><a class="nav-link" href="#worked-example-2"><span class="header-section-number">13.2.4</span> Worked Example</a></li>
</ul>
</li>
<li><a class="nav-link" href="#parametric-vs-non-parametric-methods"><span class="header-section-number">13.3</span> Parametric Vs Non-Parametric Methods</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>STAT 3080: From Data to Knowledge</strong>" was written by Jeffrey Woo. It was last built on 2026-10-02.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
