<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 14 Hypothesis Testing for Means | STAT 3080: From Data to Knowledge</title>
<meta name="author" content="Jeffrey Woo">
<meta name="description" content="14.1 Introduction Consider this scenario: you are conducting clinical trials to assess whether a new vaccine is more effective than existing vaccines. Suppose the efficacy of existing vaccines on...">
<meta name="generator" content="bookdown 0.34 with bs4_book()">
<meta property="og:title" content="Chapter 14 Hypothesis Testing for Means | STAT 3080: From Data to Knowledge">
<meta property="og:type" content="book">
<meta property="og:description" content="14.1 Introduction Consider this scenario: you are conducting clinical trials to assess whether a new vaccine is more effective than existing vaccines. Suppose the efficacy of existing vaccines on...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 14 Hypothesis Testing for Means | STAT 3080: From Data to Knowledge">
<meta name="twitter:description" content="14.1 Introduction Consider this scenario: you are conducting clinical trials to assess whether a new vaccine is more effective than existing vaccines. Suppose the efficacy of existing vaccines on...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.4.2/transition.js"></script><script src="libs/bs3compat-0.4.2/tabs.js"></script><script src="libs/bs3compat-0.4.2/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">STAT 3080: From Data to Knowledge</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Preface</a></li>
<li><a class="" href="Rbasics.html"><span class="header-section-number">1</span> R Basics</a></li>
<li><a class="" href="rmd.html"><span class="header-section-number">2</span> R Markdown</a></li>
<li><a class="" href="subset.html"><span class="header-section-number">3</span> Working with Data Structures</a></li>
<li><a class="" href="func.html"><span class="header-section-number">4</span> Functions</a></li>
<li><a class="" href="control.html"><span class="header-section-number">5</span> Control Flow</a></li>
<li><a class="" href="sims.html"><span class="header-section-number">6</span> Simulations</a></li>
<li><a class="" href="applyfam.html"><span class="header-section-number">7</span> Apply Family</a></li>
<li><a class="" href="ggplot.html"><span class="header-section-number">8</span> Data Visualizations (ggplot2)</a></li>
<li><a class="" href="dplyr.html"><span class="header-section-number">9</span> Data Wrangling (dplyr)</a></li>
<li><a class="" href="EDA.html"><span class="header-section-number">10</span> Exploratory Data Analysis and Tidying Data</a></li>
<li><a class="" href="clt.html"><span class="header-section-number">11</span> Sampling Distributions and the Central Limit Theorem</a></li>
<li><a class="" href="CI.html"><span class="header-section-number">12</span> Confidence Intervals</a></li>
<li><a class="" href="boot.html"><span class="header-section-number">13</span> The Bootstrap</a></li>
<li><a class="active" href="hyp.html"><span class="header-section-number">14</span> Hypothesis Testing for Means</a></li>
<li><a class="" href="prac.html"><span class="header-section-number">15</span> Type I and II Errors, Significance Level, Power</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="hyp" class="section level1" number="14">
<h1>
<span class="header-section-number">14</span> Hypothesis Testing for Means<a class="anchor" aria-label="anchor" href="#hyp"><i class="fas fa-link"></i></a>
</h1>
<div id="introduction-4" class="section level2" number="14.1">
<h2>
<span class="header-section-number">14.1</span> Introduction<a class="anchor" aria-label="anchor" href="#introduction-4"><i class="fas fa-link"></i></a>
</h2>
<p>Consider this scenario: you are conducting clinical trials to assess whether a new vaccine is more effective than existing vaccines. Suppose the efficacy of existing vaccines on a certain disease is 80%, and you conduct clinical trials on 30 patients, and the new vaccine is effective on 25 patients. How strong is this result in trying to prove that the new vaccine is more effective than existing vaccines? Questions like these lead to hypothesis testing.</p>
<p>In previous modules, we have established the fact that estimators are likely to deviate from the value from their corresponding parameter, due to random sampling. Confidence intervals allow us to provide a measure of uncertainty over our estimator as well as a range of plausible values for the parameter, using concepts regarding the sampling distribution of estimators. These concepts can also be used to assess whether our observed value for the estimator is different enough from a potential value of the parameter that random sampling alone is unlikely to be the only reason for the difference. Once this assessment is done, we then want to make a conclusion and decision about the unknown parameter. This is the big picture idea behind hypothesis testing. <strong>Hypothesis testing</strong> is a method for making a systematic decision with statistical guarantees.</p>
<p>Hypothesis testing typically has the following steps:</p>
<ol style="list-style-type: decimal">
<li>State a hypothesis, based on the research question.</li>
<li>Assume the hypothesis is true, and then compute a metric that measures how much our observed data deviates from the assumed hypothesis.</li>
<li>Compare the metric with some sort of threshold to assess if our observed data deviates “far enough” from the assumed hypothesis, and then make a decision.</li>
</ol>
<p>For ease of exposition, we will introduce these ideas in the framework of the hypothesis test for the mean. We then show how the framework applies in two other situations: hypothesis test for paired means and hypothesis test for two independent means.</p>
<p>A hypothesis is a statement which we assess whether is true or not using our observed data. In the framework of hypothesis testing, we state two competing hypotheses:</p>
<ul>
<li><p>The first hypothesis is the <strong>null hypothesis</strong>. This is normally the “status quo”.</p></li>
<li><p>The other hypothesis is the <strong>alternative hypothesis</strong>. This can be viewed as a statement that is “opposite” of the null hypothesis.</p></li>
</ul>
<p>Many authors present these hypotheses and hypothesis testing using a court trial as an analogy. Defendants are assumed to be “innocent until proven guilty”. The “null hypothesis” or status quo in this setting is that the defendant is innocent, and the “alternative hypothesis” is that the defendant is guilty. The prosecutor needs to then present evidence that contradicts the null hypothesis in order to prove guilt. The jurors, who come into the trial assuming the defendant is innocent, then assess how strong is the evidence presented: if its strength is beyond a certain threshold (i.e. beyond “reasonable doubt”) then there is evidence to reject the null hypothesis and decide the defendant is guilty. However, if the evidence is not strong enough, there is not enough evidence to reject the null hypothesis and the jury renders a not guilty verdict.</p>
</div>
<div id="testmean" class="section level2" number="14.2">
<h2>
<span class="header-section-number">14.2</span> Hypothesis Test for the Mean<a class="anchor" aria-label="anchor" href="#testmean"><i class="fas fa-link"></i></a>
</h2>
<p>When testing for the mean, the parameter is the population mean. This happens when the variable we are measuring is quantitative. Consider this example:</p>
<p>The term “Freshman 15” is an expression which says that college students gain 15 pounds (on average), in their first year in college. Researchers claim that with better education regarding healthier lifestyle habits, this gain is less than 15 pounds, on average.</p>
<p>We will conduct a hypothesis test for the mean. Some authors call this a 1-sample <span class="math inline">\(t\)</span> test for the mean, since it involves only 1 sample (college students) and is based on the <span class="math inline">\(t\)</span> distribution.</p>
<p>Next, we cover the first step in hypothesis testing: how to write the null and alternative hypothesis statements.</p>
<div id="null-and-alternative-hypotheses" class="section level3" number="14.2.1">
<h3>
<span class="header-section-number">14.2.1</span> Null and Alternative Hypotheses<a class="anchor" aria-label="anchor" href="#null-and-alternative-hypotheses"><i class="fas fa-link"></i></a>
</h3>
<p>Null and alternative hypotheses are statements regarding the value of a parameter.</p>
<p>For the Freshman 15 example, the null hypothesis is that the average weight gain for first year college students is 15 pounds. This is denoted as <span class="math inline">\(H_0: \mu = 15\)</span>, where <span class="math inline">\(H_0\)</span> denotes the null hypothesis. The alternative hypothesis is that the average weight gain for first year college students is less than 15 pounds. This is denoted as <span class="math inline">\(H_a: \mu &lt; 15\)</span>, where <span class="math inline">\(H_a\)</span> denotes the alternative hypothesis.</p>
<div id="features-of-null-and-alternative-hypotheses" class="section level4" number="14.2.1.1">
<h4>
<span class="header-section-number">14.2.1.1</span> Features of Null and Alternative Hypotheses<a class="anchor" aria-label="anchor" href="#features-of-null-and-alternative-hypotheses"><i class="fas fa-link"></i></a>
</h4>
<ul>
<li><p>Null and alternative hypotheses are always about a population parameter, not a sample estimator. The reason is that we want to make a claim about the population, based on data in our sample. Notice in the Freshman 15 example, that our null and alternative hypotheses are about the population mean <span class="math inline">\(\mu\)</span> and not the sample mean <span class="math inline">\(\bar{x}\)</span>.</p></li>
<li><p>The <strong>null hypothesis</strong> is a statement that says the parameter is equal to some specific value. Let <span class="math inline">\(\mu_0\)</span> denote this specific value. So we write <span class="math inline">\(H_0: \mu = \mu_0\)</span>. In the Freshman 15 example, <span class="math inline">\(\mu_0 = 15\)</span>.</p></li>
<li>
<p>The <strong>alternative hypothesis</strong> is a statement against the null hypothesis. For the hypothesis test for the mean, there are a few possible alternative hypotheses. Which one we use is <strong>driven by the research question</strong>. The alternative hypothesis could say the parameter is:</p>
<ul>
<li><p>Different from some specific value, i.e. <span class="math inline">\(H_a: \mu \neq \mu_0\)</span>. This is called a <strong>two-sided alternative</strong> since the parameter could be greater or less than some specific value.</p></li>
<li><p>Greater than some specific value, i.e. <span class="math inline">\(H_a: \mu &gt; \mu_0\)</span>. This is called a <strong>one-sided alternative</strong> since the parameter is greater than some specific value.</p></li>
<li><p>Less than some specific value, i.e. <span class="math inline">\(H_a: \mu &lt; \mu_0\)</span>. This is also called a one-sided alternative since the parameter is less than some specific value.</p></li>
</ul>
</li>
</ul>
<p>So for the hypothesis test for the mean, there are 3 options for the alternative hypothesis.</p>
<p>In the Freshman 15 example, researchers claim that with better education, the average weight gain is less than 15 pounds, so that is why we write <span class="math inline">\(H_a: \mu &lt; 15\)</span>.</p>
</div>
<div id="some-comments-about-the-null-hypothesis-with-a-one-sided-alternative" class="section level4" number="14.2.1.2">
<h4>
<span class="header-section-number">14.2.1.2</span> Some Comments about the Null Hypothesis with a One-sided Alternative<a class="anchor" aria-label="anchor" href="#some-comments-about-the-null-hypothesis-with-a-one-sided-alternative"><i class="fas fa-link"></i></a>
</h4>
<p>A number of textbooks take the view that the null and alternative hypotheses are complements, so if we write <span class="math inline">\(H_a: \mu &lt; \mu_0\)</span>, then we must write <span class="math inline">\(H_0: \mu \geq \mu_0\)</span>. This way of writing a null hypothesis is different from that I wrote earlier: that the null hypothesis says the parameter is equal to <span class="math inline">\(\mu_0\)</span>. There are a couple of reasons why I say the null hypothesis is a statement involving an equality, rather than an inequality:</p>
<ol style="list-style-type: decimal">
<li><p>The calculations performed to assess the evidence our data provides are done assuming the null hypothesis is true. You will realize in the later subsections that one can only perform these calculations if the null hypothesis says the parameter is equal to some specific value.</p></li>
<li><p>I have seen many people get confused with the null and alternative hypotheses if they insist the null and alternative must be opposite with a one-sided alternative. Indeed, if you look at Practice Exercise 9.3 and 9.4 in our book, the author has gotten these confused in the proposed solutions.</p></li>
</ol>
</div>
</div>
<div id="test-statistic" class="section level3" number="14.2.2">
<h3>
<span class="header-section-number">14.2.2</span> Test Statistic<a class="anchor" aria-label="anchor" href="#test-statistic"><i class="fas fa-link"></i></a>
</h3>
<p>After writing the null and alternative hypotheses, the next step is to compute a value that measures how far our sample data are from their expected value if the null hypothesis is true. This value is called the <strong>test statistic</strong>. How a test statistic is calculated is based on the sampling distribution of the estimator being used.</p>
<p>We remind ourselves of the sampling distribution of the sample mean, <span class="math inline">\(\bar{X}_n\)</span>, from Section <a href="clt.html#distsampmean">11.3</a>. There are a couple of conditions to consider:</p>
<ol style="list-style-type: decimal">
<li><p><span class="math inline">\(X_1, \cdots, X_n\)</span> are i.i.d. from a normal distribution with finite mean <span class="math inline">\(\mu\)</span> and finite variance <span class="math inline">\(\sigma^2\)</span>. Then <span class="math inline">\(\bar{X}_n \sim N(\mu, \frac{\sigma^2}{n})\)</span>.</p></li>
<li><p><span class="math inline">\(X_1, \cdots, X_n\)</span> are i.i.d. from any distribution with finite mean <span class="math inline">\(\mu\)</span> and finite variance <span class="math inline">\(\sigma^2\)</span>, and if <span class="math inline">\(n\)</span> is large enough, then <span class="math inline">\(\bar{X}_n\)</span> is approximately <span class="math inline">\(N(\mu, \frac{\sigma^2}{n})\)</span>.</p></li>
</ol>
<p>If either of these conditions are met, then the distribution of <span class="math inline">\(\bar{X}_n\)</span> after standardization is either a standard normal or approaches a standard normal distribution, so <span class="math inline">\(\frac{\bar{X}_n - \mu}{\frac{\sigma}{\sqrt{n}}} = \frac{\bar{X}_n - \mu}{\sqrt{Var(\bar{X})}} = \frac{\bar{X}_n - \mu}{SE(\bar{X}_n)}\)</span> is either standard normal or approximately standard normal when <span class="math inline">\(n\)</span> is large enough.</p>
<p>We then learned in Section <a href="CI.html#CImeant">12.2.4</a> that since the value of the population variance <span class="math inline">\(\sigma^2\)</span> is almost always unknown in real life, we use the sample variance <span class="math inline">\(s^2\)</span> instead. So we work with <span class="math inline">\(\frac{\bar{X}_n - \mu}{\frac{s}{\sqrt{n}}}\)</span> instead, which follows a <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(n-1\)</span> degrees of freedom.</p>
<p>Based on this distribution, the test statistic for a hypothesis test for the mean is</p>
<p><span class="math display" id="eq:9-teststatMean">\[\begin{equation}
\hat{t} =  \frac{\bar{x}_n - \mu_0}{\frac{s}{\sqrt{n}}} = \frac{\bar{x}_n - \mu_0}{SE(\bar{x}_n)},
\tag{14.1}
\end{equation}\]</span></p>
<p>where <span class="math inline">\(SE(\bar{x}_n)\)</span> is <span class="math inline">\(\frac{s}{\sqrt{n}}\)</span>. This can be called a <strong><span class="math inline">\(t\)</span> statistic</strong> to reflect that our test statistic is based on the <span class="math inline">\(t\)</span> distribution. The <span class="math inline">\(t\)</span> statistic follows a <span class="math inline">\(t_{n-1}\)</span> distribution (the subscript refers to the degrees of freedom) if either of the 2 conditions are met for the sampling distribution of <span class="math inline">\(\bar{X}_n\)</span> to be valid, and if we assume the null hypothesis is true, that the true mean of the data is <span class="math inline">\(\mu_0\)</span>.</p>
<p>Note: A number of hypothesis tests involving other estimators and parameters are also based on the <span class="math inline">\(t_{df}\)</span> distribution, and have their own <span class="math inline">\(t\)</span> statistics. However, <span class="math inline">\(t\)</span> statistics will take on the general form</p>
<p><span class="math display" id="eq:9-tstatGen">\[\begin{equation}
\hat{t} =  \frac{\text{estimated value }- \text{ value in } H_0}{\text{standard error of estimator}}.
\tag{14.2}
\end{equation}\]</span></p>
<p>Notice how equation <a href="hyp.html#eq:9-tstatGen">(14.2)</a> is a generalization of equation <a href="hyp.html#eq:9-teststatMean">(14.1)</a>.</p>
<p>Note: A variation of this test is the 1-sample <span class="math inline">\(z\)</span>-test for the mean. This assumes the population standard deviation is known, but that is unlikely in reality. The sample standard deviation in equation <a href="hyp.html#eq:9-teststatMean">(14.1)</a> is replaced by the population standard deviation and the test statistic becomes a <span class="math inline">\(Z\)</span> statistic as it is compared with a standard normal distribution.</p>
<p>We go back to the Freshman 15 example. Suppose researchers collect a random sample of 50 first-year college students. Their average weight gain is 14 pounds, with standard deviation of 3 pounds. Derive the value of the <span class="math inline">\(t\)</span> statistic.</p>
<p>Using equation <a href="hyp.html#eq:9-teststatMean">(14.1)</a>, the <span class="math inline">\(t\)</span> statistic is:</p>
<p><span class="math display">\[
\begin{split}
\hat{t} &amp;= \frac{14-15}{\frac{3}{\sqrt{50}}} \\
        &amp;= -2.357023.
\end{split}
\]</span>
This <span class="math inline">\(t\)</span> statistic is valid since our sample size is 50, which is usually large enough for the approximation to the <span class="math inline">\(t\)</span> distribution to be valid.</p>
<p>Remember that the test statistic is a measure of how far our sample data are from their expected value if the null hypothesis is true. Larger values of the test statistic (in magnitude) imply that our data deviate further from the null hypothesis, i.e. our data provide more evidence against the null hypothesis.</p>
<p>The <span class="math inline">\(t\)</span> statistic also has this nice definition: it is the distance between our sample estimator and the value of the parameter if the null hypothesis is true, in terms of number of standard errors. So for our Freshman 15 example, the sample mean is 2.357 standard errors smaller than the hypothesized value of 15.</p>
<div id="factors" class="section level4" number="14.2.2.1">
<h4>
<span class="header-section-number">14.2.2.1</span> Factors Affecting <span class="math inline">\(t\)</span> Statistic for Mean<a class="anchor" aria-label="anchor" href="#factors"><i class="fas fa-link"></i></a>
</h4>
<p>We have established that larger values of the test statistic (in magnitude) imply more evidence against the null hypothesis. For the <span class="math inline">\(t\)</span> statistic for the mean, the factors that affect its magnitude are:</p>
<ul>
<li><p>The difference between the sample mean <span class="math inline">\(\bar{x}\)</span> of our data and the value of the population mean if the null is true <span class="math inline">\(\mu_0\)</span>. This difference is called the <strong>effect size</strong>. Larger effect sizes lead to larger test statistics, in magnitude. This should make sense since a larger effect size implies the sample mean deviates more from the expected mean if the null hypothesis is true.</p></li>
<li><p>The sample size <span class="math inline">\(n\)</span>. Larger sample sizes lead to larger magnitudes for the <span class="math inline">\(t\)</span> statistic, since <span class="math inline">\(\frac{\bar{x}_n - \mu_0}{\frac{s}{\sqrt{n}}}\)</span> can be written as <span class="math inline">\(\sqrt{n}\frac{\bar{x}_n - \mu_0}{s}\)</span>. This implies that even if the effect size stays the same, larger sample sizes provide more evidence against the null.</p></li>
</ul>
</div>
</div>
<div id="decision" class="section level3" number="14.2.3">
<h3>
<span class="header-section-number">14.2.3</span> Making a Decision<a class="anchor" aria-label="anchor" href="#decision"><i class="fas fa-link"></i></a>
</h3>
<p>After calculating the value of the test statistic, we need to assess if our data provide enough evidence against the null hypothesis or not. There are two approaches to making this assessment: one involves the p-value, and the other involves the critical value.</p>
<ul>
<li>Using the p-value, we <strong>reject the null hypothesis if our p-value is less than the significance level</strong> (i.e. our data have enough evidence against the null hypothesis). Otherwise, we fail to reject the null hypothesis (i.e. our data do not have enough evidence against the null hypothesis)</li>
</ul>
<p>The <strong>significance level</strong> of the test, denoted by <span class="math inline">\(\alpha\)</span>, is the probability of wrongly rejecting the null hypothesis when the null hypothesis is actually true. This error is called a type I error, which we will define more formally in a later subsection. So if we conduct a hypothesis test with significance level <span class="math inline">\(\alpha = 0.05\)</span>, we are saying that we are willing to have a 5% probability of wrongly concluding that we have enough evidence against the null hypothesis, when it is actually true.</p>
<ul>
<li>Using the critical value, we <strong>reject the null hypothesis if our test statistic is more extreme than the critical value in the direction of the alternative hypothesis</strong> (i.e. our data have enough evidence against the null hypothesis). Otherwise, we fail to reject the null hypothesis (i.e. our data do not have enough evidence against the null hypothesis).</li>
</ul>
<p>Both of these approaches are based on the sampling distribution of the estimator, and on the value of the significance level. Both of these approaches will always lead to the same conclusion, so you only need to use one of them.</p>
<div id="p-value" class="section level4" number="14.2.3.1">
<h4>
<span class="header-section-number">14.2.3.1</span> P-Value<a class="anchor" aria-label="anchor" href="#p-value"><i class="fas fa-link"></i></a>
</h4>
<p>The <strong>p-value</strong> is the probability of observing the value of our test statistic, or a value more extreme in the direction of the alternative hypothesis, if the null hypothesis is true.</p>
<p>Informally, this is also the probability of observing the value of our sample mean, or a value more extreme in the direction of the alternative hypothesis, if the null hypothesis is true.</p>
<p>Recall that for a hypothesis test of the mean, the <span class="math inline">\(t\)</span> statistic follows a <span class="math inline">\(t_{n-1}\)</span> distribution, as our calculations assume the null hypothesis is true. Visually, we can use areas under the PDF of a <span class="math inline">\(t_{n-1}\)</span> to illustrate how the p-value is found. The specific area under the PDF depends on which of the three alternative hypotheses we are using. In Figures <a href="hyp.html#fig:9-pvalneq">14.1</a>, <a href="hyp.html#fig:9-pvalgreater">14.2</a>, and <a href="hyp.html#fig:9-pvalless">14.3</a> below, we have examples on the relevant areas under the PDF if the value of the <span class="math inline">\(t\)</span> statistic is <span class="math inline">\(\hat{t} = 1\)</span>.</p>
<ol style="list-style-type: decimal">
<li>If <span class="math inline">\(H_a: \mu \neq \mu_0\)</span>, i.e. we have a two-sided alternative, the corresponding areas under the PDF of the <span class="math inline">\(t_{n-1}\)</span> distribution that is the p-value is shown below in Figure <a href="hyp.html#fig:9-pvalneq">14.1</a>:</li>
</ol>
<div class="figure">
<span style="display:block;" id="fig:9-pvalneq"></span>
<img src="bookdown-demo_files/figure-html/9-pvalneq-1.png" alt="Finding P-value, with Two-Sided Alternative" width="672"><p class="caption">
Figure 14.1: Finding P-value, with Two-Sided Alternative
</p>
</div>
<p>It is the area to the right of <span class="math inline">\(|\hat{t}|\)</span> and the area to the left of -<span class="math inline">\(|\hat{t}|\)</span>. Using probability notation, this is <span class="math inline">\(P(|t_{n-1}| \geq 1)\)</span>.</p>
<ol start="2" style="list-style-type: decimal">
<li>If <span class="math inline">\(H_a: \mu &gt; \mu_0\)</span>, i.e. the population mean is greater than a specified value, the corresponding area under the PDF of the <span class="math inline">\(t_{n-1}\)</span> distribution that is the p-value is shown below in Figure <a href="hyp.html#fig:9-pvalgreater">14.2</a>:</li>
</ol>
<div class="figure">
<span style="display:block;" id="fig:9-pvalgreater"></span>
<img src="bookdown-demo_files/figure-html/9-pvalgreater-1.png" alt="Finding P-value, with Greater Than Alternative" width="672"><p class="caption">
Figure 14.2: Finding P-value, with Greater Than Alternative
</p>
</div>
<p>It is the area to the right of <span class="math inline">\(\hat{t}\)</span>. Using probability notation, this is <span class="math inline">\(P(t_{n-1} \geq 1)\)</span>.</p>
<ol start="3" style="list-style-type: decimal">
<li>If <span class="math inline">\(H_a: \mu &lt; \mu_0\)</span>, i.e. the population mean is less than a specified value, the corresponding area under the PDF of the <span class="math inline">\(t_{n-1}\)</span> distribution that is the p-value is shown below in Figure <a href="hyp.html#fig:9-pvalless">14.3</a>:</li>
</ol>
<div class="figure">
<span style="display:block;" id="fig:9-pvalless"></span>
<img src="bookdown-demo_files/figure-html/9-pvalless-1.png" alt="Finding P-value, with Less Than Alternative" width="672"><p class="caption">
Figure 14.3: Finding P-value, with Less Than Alternative
</p>
</div>
<p>It is the area to the left of <span class="math inline">\(\hat{t}\)</span>. Using probability notation, this is <span class="math inline">\(P( t_{n-1} \leq 1)\)</span>.</p>
<p>Going back to the Freshman 15 example, we found the <span class="math inline">\(t\)</span> statistic to be −2.357023. We had earlier written the alternative hypothesis as <span class="math inline">\(H_a: \mu &lt; 15\)</span>, so we find the PDF under a <span class="math inline">\(t_{49}\)</span> distribution using the area to the left of <span class="math inline">\(-2.357023\)</span>, in a manner similar to Figure <a href="hyp.html#fig:9-pvalless">14.3</a>.</p>
<div class="figure">
<span style="display:block;" id="fig:9-pvaleg"></span>
<img src="bookdown-demo_files/figure-html/9-pvaleg-1.png" alt="Finding P-value, For Freshman 15 Example" width="672"><p class="caption">
Figure 14.4: Finding P-value, For Freshman 15 Example
</p>
</div>
<p>Using R, this p-value is 0.01123. If our test is conducted at 5% significance level, we reject the null hypothesis, since this p-value is less than 0.05.</p>
<div class="sourceCode" id="cb494"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">pt</a></span><span class="op">(</span><span class="op">-</span><span class="fl">2.357023</span>, <span class="fl">49</span><span class="op">)</span> <span class="co">##enter t stat, then df</span></span></code></pre></div>
<pre><code>## [1] 0.01123111</code></pre>
<p><strong>Thought question</strong>: Suppose the research question for the Freshman 15 example was tweaked, so the alternative hypothesis is <span class="math inline">\(H_a:\mu &gt; 15\)</span>. Assuming everything else stays the same, show that the p-value is now 0.98877. If the alternative hypothesis is <span class="math inline">\(H_a: \mu \neq 15\)</span>, show that the p-value is 0.02246.</p>
</div>
<div id="critical-value-1" class="section level4" number="14.2.3.2">
<h4>
<span class="header-section-number">14.2.3.2</span> Critical Value<a class="anchor" aria-label="anchor" href="#critical-value-1"><i class="fas fa-link"></i></a>
</h4>
<p>Informally, the critical value is the value of the test statistic that is considered “enough” to say that we have enough evidence against the null hypothesis to reject it, based on the value of the significance level.</p>
<p>We use the PDF of a <span class="math inline">\(t\)</span> distribution to visualize what a critical value is. We want to find the “cut off” value, denoted by <span class="math inline">\(t_{n-1}^*\)</span>, of the distribution where the area under its PDF in the direction of the alternative hypothesis is equal to the significance level <span class="math inline">\(\alpha\)</span>. Since we have three options for the alternative hypothesis, we have 3 different areas under the PDF to consider. In Figures <a href="hyp.html#fig:9-critneq">14.5</a>, <a href="hyp.html#fig:9-critgreater">14.6</a>, and <a href="hyp.html#fig:9-critless">14.7</a> below, we have examples on the relevant areas under the PDF if <span class="math inline">\(\alpha=0.05\)</span> and <span class="math inline">\(n=50\)</span>:</p>
<ol style="list-style-type: decimal">
<li>If <span class="math inline">\(H_a: \mu \neq \mu_0\)</span>, i.e. we have a two-sided alternative, we want the areas under the PDF of the <span class="math inline">\(t_{49}\)</span> distribution to the right of <span class="math inline">\(t_{49}^*\)</span> and to the left of <span class="math inline">\(-t_{49}^*\)</span> to be equal to 0.05. This is shown in Figure <a href="hyp.html#fig:9-critneq">14.5</a>:</li>
</ol>
<div class="figure">
<span style="display:block;" id="fig:9-critneq"></span>
<img src="images/09-crit_2sided.jpeg" alt="Critical Value for 2-Sided Alternative, with 0.05 Sig Level"><p class="caption">
Figure 14.5: Critical Value for 2-Sided Alternative, with 0.05 Sig Level
</p>
</div>
<p>Note that since the <span class="math inline">\(t\)</span> distribution is symmetric and both areas in blue add up to 0.05, each shaded area must be 0.025. So <span class="math inline">\(-t_{49}^*\)</span> and <span class="math inline">\(t_{49}^*\)</span> correspond to the 2.5th and 97.5th percentiles of a <span class="math inline">\(t_{49}\)</span> distribution respectively. We can show that <span class="math inline">\(-t_{49}^*\)</span> is -2.009575 by typing</p>
<div class="sourceCode" id="cb496"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">alpha</span><span class="op">&lt;-</span><span class="fl">0.05</span></span>
<span><span class="va">n</span><span class="op">&lt;-</span><span class="fl">50</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="va">alpha</span><span class="op">/</span><span class="fl">2</span>, <span class="va">n</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] -2.009575</code></pre>
<p>and by symmetry of the <span class="math inline">\(t\)</span> distribution, <span class="math inline">\(t_{49}^*\)</span> is 2.009575. The critical value is therefore <span class="math inline">\(t_{49}^* = 2.009575\)</span> for a 2-sided test. We will reject the null hypothesis if our <span class="math inline">\(t\)</span> statistic is to the right of 2.009575 or if it is to the left of -2.009575.</p>
<p>In general, for any significance level <span class="math inline">\(\alpha\)</span>, the negative critical value <span class="math inline">\(-t_{n-1}^*\)</span> corresponds to the <span class="math inline">\((\alpha/2) \times 100\)</span>th percentile, and the positive critical value <span class="math inline">\(t_{n-1}^*\)</span> corresponds to the <span class="math inline">\((1 - \alpha/2) \times 100\)</span>th percentile of the appropriate <span class="math inline">\(t_{n-1}\)</span> distribution, if <span class="math inline">\(H_a: \mu \neq \mu_0\)</span>.</p>
<ol start="2" style="list-style-type: decimal">
<li>If <span class="math inline">\(H_a: \mu &gt; \mu_0\)</span>, i.e. the population mean is greater than some specified value, we want the area under the PDF of the <span class="math inline">\(t_{49}\)</span> distribution to the right of <span class="math inline">\(t_{49}^*\)</span> to be equal to 0.05. This is shown in Figure <a href="hyp.html#fig:9-critgreater">14.6</a>:</li>
</ol>
<div class="figure">
<span style="display:block;" id="fig:9-critgreater"></span>
<img src="images/09-crit_greater.jpeg" alt="Critical Value for Greater Than Alternative, with 0.05 Sig Level"><p class="caption">
Figure 14.6: Critical Value for Greater Than Alternative, with 0.05 Sig Level
</p>
</div>
<p>Note that <span class="math inline">\(t_{49}^*\)</span> corresponds to the 95th percentile of a <span class="math inline">\(t_{49}\)</span> distribution. We can show that <span class="math inline">\(t_{49}^*\)</span> is 1.677 by typing</p>
<div class="sourceCode" id="cb498"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">alpha</span><span class="op">&lt;-</span><span class="fl">0.05</span></span>
<span><span class="va">n</span><span class="op">&lt;-</span><span class="fl">50</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fl">1</span><span class="op">-</span><span class="va">alpha</span>, <span class="va">n</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 1.676551</code></pre>
<p>The critical value is therefore <span class="math inline">\(t_{49}^* = 1.676551\)</span> when <span class="math inline">\(H_a: \mu &gt; \mu_0\)</span>. We will reject the null hypothesis if our <span class="math inline">\(t\)</span> statistic is to the right of 1.676551.</p>
<p>In general, for any significance level <span class="math inline">\(\alpha\)</span>, the critical value <span class="math inline">\(t_{n-1}^*\)</span> corresponds to the <span class="math inline">\((1 - \alpha) \times 100\)</span>th percentile of the appropriate <span class="math inline">\(t_{n-1}\)</span> distribution, if <span class="math inline">\(H_a: \mu &gt; \mu_0\)</span>.</p>
<ol start="3" style="list-style-type: decimal">
<li>If <span class="math inline">\(H_a: \mu &lt; \mu_0\)</span>, i.e. the population mean is less than some specified value, we want the area under the PDF of the <span class="math inline">\(t_{49}\)</span> distribution to the left of <span class="math inline">\(t_{49}^*\)</span> to be equal to 0.05. This is shown in Figure <a href="hyp.html#fig:9-critless">14.7</a>:</li>
</ol>
<div class="figure">
<span style="display:block;" id="fig:9-critless"></span>
<img src="images/09-crit_less.jpeg" alt="Critical Value for Less Than Alternative, with 0.05 Sig Level"><p class="caption">
Figure 14.7: Critical Value for Less Than Alternative, with 0.05 Sig Level
</p>
</div>
<p>Note that <span class="math inline">\(t_{49}^*\)</span> corresponds to the 5th percentile of a <span class="math inline">\(t_{49}\)</span> distribution. We can show that <span class="math inline">\(t_{49}^*\)</span> is -1.677 by typing</p>
<div class="sourceCode" id="cb500"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">alpha</span><span class="op">&lt;-</span><span class="fl">0.05</span></span>
<span><span class="va">n</span><span class="op">&lt;-</span><span class="fl">50</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="va">alpha</span>, <span class="va">n</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] -1.676551</code></pre>
<p>The critical value is therefore <span class="math inline">\(t_{49}^* = -1.676551\)</span> when <span class="math inline">\(H_a: \mu &lt; \mu_0\)</span>. We will reject the null hypothesis if our <span class="math inline">\(t\)</span> statistic is to the left of -1.676551.</p>
<p>In general, for any significance level <span class="math inline">\(\alpha\)</span>, the critical value <span class="math inline">\(t_{n-1}^*\)</span> corresponds to the <span class="math inline">\((\alpha) \times 100\)</span>th percentile of the appropriate <span class="math inline">\(t_{n-1}\)</span> distribution, if <span class="math inline">\(H_a: \mu &lt; \mu_0\)</span>.</p>
<p>Going back to the Freshman 15 example, we found the <span class="math inline">\(t\)</span> statistic to be −2.357023. We had earlier written the alternative hypothesis as <span class="math inline">\(H_a: \mu &lt; 15\)</span>, so the critical value is the 5th percentile of a <span class="math inline">\(t_{49}\)</span> distribution, which we found to be -1.676551. Since our <span class="math inline">\(t\)</span> statistic is to the left of this critical value, we reject the null hypothesis.</p>
<p><strong>Thought question</strong>: Consider a hypothesis test for the mean with <span class="math inline">\(n=10\)</span>. Assume the conditions for the sampling distribution of the sample mean to be met. Suppose <span class="math inline">\(\alpha=0.10\)</span>. If the alternative hypothesis is 2-sided, show that the critical value is 1.833113. If the alternative hypothesis is 1-sided, show that the critical value is 1.383029.</p>
</div>
</div>
<div id="writing-conclusions" class="section level3" number="14.2.4">
<h3>
<span class="header-section-number">14.2.4</span> Writing Conclusions<a class="anchor" aria-label="anchor" href="#writing-conclusions"><i class="fas fa-link"></i></a>
</h3>
<p>In the previous subsection, we decide whether to reject the null hypothesis based on two approaches:</p>
<ul>
<li>If the p-value of our test is less than the significance level.</li>
<li>If the test statistic of our test is more extreme than the critical value, in the direction of the alternative hypothesis.</li>
</ul>
<p>The decision based on both approaches should always be the same and never contradict each other. All you need is to use one of these approaches, the other is redundant. It is up to you to choose which one you want to use, but you must be clear which one you are using.</p>
<p>We decide between:</p>
<ol style="list-style-type: decimal">
<li><p>Rejecting the null hypothesis. This implies that we have enough evidence against the null hypothesis to reject it and support the alternative hypothesis. Our data support the claim in the alternative hypothesis. Using the court trial analogy, this is equivalent to saying we have enough evidence to prove a defendants guilt as we reject the assumption that the defendant is innocent, and give a guilty verdict.</p></li>
<li><p>Failing to reject the null hypothesis. This implies that we do not have enough evidence against the null hypothesis and so we do not reject it. Our data do not support the claim in the alternative hypothesis. Using the court trial analogy, this is equivalent to saying we do not have enough evidence to prove a defendants and so give a not guilty verdict.</p></li>
</ol>
<p>A common mistake with failing to reject the null hypothesis is to say that our data support and proves the null hypothesis is true. Using the court trial analogy, a not guilty verdict is not the same as saying the defendant is innocent.</p>
<p>After making a decision, we write a conclusion in the context of our research question. Using the Freshman 15 example, we rejected the null hypothesis. So our conclusion is our data support the claim that the average weight gain among first-year college students is less than 15 pounds.</p>
<p>We look at one more example to show how a hypothesis test is done from start to finish.</p>
</div>
<div id="eg1samplet" class="section level3" number="14.2.5">
<h3>
<span class="header-section-number">14.2.5</span> Worked Example<a class="anchor" aria-label="anchor" href="#eg1samplet"><i class="fas fa-link"></i></a>
</h3>
<p>A university bookstore claims that, on average, a student will pay $101.75 per class for textbooks. The student newspaper suspects that the claimed average is too low and investigates by randomly selecting 9 courses from the current semester offerings and finding the textbook costs for each. The students conducting the investigation reason that with the collection of courses being offered courses, the textbook prices are normally distributed.</p>
<p>We have one quantitative variable, the amount of money students will pay per class for textbooks. A t-test for a mean is appropriate since textbook prices are normally distributed.</p>
<p>From the question, we have <span class="math inline">\(H_0: \mu = 101.75, H_a: \mu &gt; 101.75\)</span>.</p>
<div class="sourceCode" id="cb502"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">## Record sample data collected</span></span>
<span><span class="va">news.samp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">140</span>, <span class="fl">125</span>, <span class="fl">150</span>, <span class="fl">87</span>, <span class="fl">170</span>, <span class="fl">195</span>, <span class="fl">94</span>, <span class="fl">127</span>, <span class="fl">53</span><span class="op">)</span></span>
<span></span>
<span><span class="co">## Conduct hypothesis test</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">news.samp</span>, mu<span class="op">=</span><span class="fl">101.75</span>, alternative<span class="op">=</span><span class="st">"greater"</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  news.samp
## t = 1.7147, df = 8, p-value = 0.06237
## alternative hypothesis: true mean is greater than 101.75
## 95 percent confidence interval:
##  99.63542      Inf
## sample estimates:
## mean of x 
##  126.7778</code></pre>
<div class="sourceCode" id="cb504"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">text.test</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">news.samp</span>, mu<span class="op">=</span><span class="fl">101.75</span>, alternative<span class="op">=</span><span class="st">"greater"</span><span class="op">)</span></span>
<span><span class="va">text.test</span><span class="op">$</span><span class="va">statistic</span> <span class="co">##t stat</span></span></code></pre></div>
<pre><code>##        t 
## 1.714676</code></pre>
<div class="sourceCode" id="cb506"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">text.test</span><span class="op">$</span><span class="va">parameter</span> <span class="co">##degrees of freedom</span></span></code></pre></div>
<pre><code>## df 
##  8</code></pre>
<div class="sourceCode" id="cb508"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">text.test</span><span class="op">$</span><span class="va">p.value</span> <span class="co">##p-value</span></span></code></pre></div>
<pre><code>## [1] 0.06237429</code></pre>
<div class="sourceCode" id="cb510"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">text.test</span><span class="op">$</span><span class="va">estimate</span> <span class="co">##value of estimator (sample mean here)</span></span></code></pre></div>
<pre><code>## mean of x 
##  126.7778</code></pre>
<ul>
<li>The test statistic is $t = $ 1.7146763.</li>
<li>The p-value is 0.0623743.</li>
</ul>
<p>So we reject the null hypothesis. Our data support the student newspaper’ claim that the claimed average by the bookstore is too low.</p>
</div>
</div>
<div id="hypothesis-test-for-paired-means" class="section level2" number="14.3">
<h2>
<span class="header-section-number">14.3</span> Hypothesis Test for Paired Means<a class="anchor" aria-label="anchor" href="#hypothesis-test-for-paired-means"><i class="fas fa-link"></i></a>
</h2>
<p>The hypothesis test for paired means (also called the paired t-test or the hypothesis test for two dependent means) is a special case of the hypothesis test for the mean where instead of testing the mean of one population, the difference of two means is tested by using the differences in pairs of data points that are dependent. As this is a special case of the one-sample t-test, the same assumptions are required: the differences of the paired values are normally distributed, or if the number of paired values is large enough.</p>
<p>The test statistic is</p>
<p><span class="math display" id="eq:9-teststatPaired">\[\begin{equation}
\hat{t} =  \frac{\bar{d}_n - \mu_0}{\frac{s_d}{\sqrt{n_d}}} = \frac{\bar{d}_n - \mu_0}{SE(\bar{d}_n)},
\tag{14.3}
\end{equation}\]</span></p>
<p>where <span class="math inline">\(\bar{d}_n\)</span> denotes the sample average difference between the pairs, <span class="math inline">\(s_d\)</span> denotes the standard deviation of the differences between the pairs, <span class="math inline">\(n_d\)</span> denotes the number of pairs, and <span class="math inline">\(\mu_0\)</span> denotes the mean difference under the null hypothesis. The test statistic follows a <span class="math inline">\(t_{n_d - 1}\)</span> distribution.</p>
<p><strong>Thought question:</strong> compare equation <a href="hyp.html#eq:9-teststatPaired">(14.3)</a> with equations <a href="hyp.html#eq:9-teststatMean">(14.1)</a> and <a href="hyp.html#eq:9-tstatGen">(14.2)</a>. Do you see their similarities?</p>
<p>In order to conduct a paired t-test, the optional <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> argument <code>paired</code> should be designated as <code>TRUE</code>. When conducting a paired t-test, the data are given in two vectors (the second will be subtracted from the first position-by-position).</p>
<div id="egpairedt" class="section level3" number="14.3.1">
<h3>
<span class="header-section-number">14.3.1</span> Worked Example<a class="anchor" aria-label="anchor" href="#egpairedt"><i class="fas fa-link"></i></a>
</h3>
<p>A weight study was conducted on twins in Australia. Is there evidence that identical twins over the age of 50 have significantly different weights?</p>
<p>From the question, we have <span class="math inline">\(H_0: \mu_d = 0, H_a: \mu_d \neq 0\)</span>.</p>
<div class="sourceCode" id="cb512"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://openmx.ssri.psu.edu">OpenMx</a></span><span class="op">)</span> <span class="co">##data twinData from this package</span></span>
<span></span>
<span><span class="co">## using which is another to extract the rows that pertain to multiple conditions, we want identical twins with ages over 50.</span></span>
<span><span class="va">a</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span><span class="op">(</span><span class="op">(</span><span class="va">twinData</span><span class="op">$</span><span class="va">zygosity</span> <span class="op">==</span> <span class="st">"MZFF"</span> <span class="op">|</span> <span class="va">twinData</span><span class="op">$</span><span class="va">zygosity</span> <span class="op">==</span> <span class="st">"MZMM"</span> <span class="op">)</span> <span class="op">&amp;</span> <span class="va">twinData</span><span class="op">$</span><span class="va">age</span> <span class="op">&gt;</span> <span class="fl">50</span><span class="op">)</span></span>
<span></span>
<span><span class="co">## weights of twin 1</span></span>
<span><span class="va">wt1</span> <span class="op">&lt;-</span> <span class="va">twinData</span><span class="op">$</span><span class="va">wt1</span><span class="op">[</span><span class="va">a</span><span class="op">]</span></span>
<span></span>
<span><span class="co">## corresponding weights of twin 2</span></span>
<span><span class="va">wt2</span> <span class="op">&lt;-</span> <span class="va">twinData</span><span class="op">$</span><span class="va">wt2</span><span class="op">[</span><span class="va">a</span><span class="op">]</span></span>
<span></span>
<span><span class="co">## Conduct the hypothesis test</span></span>
<span><span class="va">pair_result</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">wt1</span>, <span class="va">wt2</span>, mu<span class="op">=</span><span class="fl">0</span>, alternative<span class="op">=</span><span class="st">"two.sided"</span>, paired<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">pair_result</span></span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  wt1 and wt2
## t = 0.49766, df = 306, p-value = 0.6191
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  -0.5773256  0.9682051
## sample estimates:
## mean difference 
##       0.1954397</code></pre>
<ul>
<li>The test statistic is $t = $ 0.497662.</li>
<li>The p-value is 0.6190797. So we fail to reject the null hypothesis. The data do not provide evidence that the weights of identical twins over 50 years old are significantly different</li>
<li>The 95% confidence interval is -0.5773256, 0.9682051. Notice how this interval contains the value under the null hypothesis, 0. The conclusion is consistent with the hypothesis test.</li>
</ul>
<p>We could have also used the $t.test()4 function a little differently. We could have found the differences in weights between each pair of twins, and then performed a 1-sample t-test on these differences.</p>
<div class="sourceCode" id="cb514"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">## do a 1 sample t test</span></span>
<span><span class="va">diffs</span> <span class="op">&lt;-</span> <span class="va">wt1</span> <span class="op">-</span> <span class="va">wt2</span></span>
<span></span>
<span><span class="va">other_result</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">diffs</span>, mu<span class="op">=</span> <span class="fl">0</span>, alternative <span class="op">=</span> <span class="st">"two.sided"</span>, paired <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">other_result</span></span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  diffs
## t = 0.49766, df = 306, p-value = 0.6191
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -0.5773256  0.9682051
## sample estimates:
## mean of x 
## 0.1954397</code></pre>
<p>Notice the results are identical in both approaches.</p>
</div>
</div>
<div id="hypothesis-test-for-difference-in-two-independent-means" class="section level2" number="14.4">
<h2>
<span class="header-section-number">14.4</span> Hypothesis Test for Difference in Two Independent Means<a class="anchor" aria-label="anchor" href="#hypothesis-test-for-difference-in-two-independent-means"><i class="fas fa-link"></i></a>
</h2>
<p>The hypothesis test for difference in two independent means (also called a 2-sample <span class="math inline">\(t\)</span>-test) compares the average of a quantitative variable across two independent populations (created by a binary variable). The condition for this test is that both populations are normally distributed, or that the sample sizes are both large enough.</p>
<p>The test statistic is</p>
<p><span class="math display" id="eq:9-teststat2Means">\[\begin{equation}
\hat{t} =  \frac{(\bar{x} - \bar{y}) - (\mu_X - \mu_Y)}{\sqrt{\frac{s_X^2}{n_X} + \frac{s_Y^2}{n_Y}}} = \frac{(\bar{x} - \bar{y}) - (\mu_X - \mu_Y)}{SE(\bar{X} - \bar{Y})},
\tag{14.4}
\end{equation}\]</span></p>
<p>where <span class="math inline">\(\bar{X}, \bar{Y}\)</span> denote the sample averages in each sample, <span class="math inline">\(s_X, s_Y\)</span> denote the standard deviation in each sample, <span class="math inline">\(n_X, n_Y\)</span> denote the sample sizes in in each sample, and <span class="math inline">\(\mu_X - \mu_Y\)</span> denotes the mean difference under the null hypothesis. The test statistic follows a <span class="math inline">\(t\)</span> distribution. The degrees of freedom is approximated using the <a href="https://en.wikipedia.org/wiki/Welch%27s_t-test#Calculations">Welch–Satterthwaite equation</a>.</p>
<p>In some older references, it is suggested to approximate the degrees of freedom using <span class="math inline">\(min(n_X, n_Y) - 1\)</span>. The hypothesis test using this approximation is considered to be more <strong>conservative</strong> than the approximation based on the Welch–Satterthwaite equation. A hypothesis test that is conservative is a test when the Type I error rate (probability of wrongly rejecting the null) is below the significance level, and is less powerful. We will cover these concepts in the next section, Section <a href="prac.html#prac">15</a>.</p>
<p><strong>Thought question:</strong> what are the factors that lead to stronger evidence against the null hypothesis for this test?</p>
<p>Similar to what we wrote in Section <a href="CI.html#pooled">12.4.1</a>, the test statistic for the difference in two independent means given in equation <a href="hyp.html#eq:9-teststat2Means">(14.4)</a> is the modern default. It is sometimes called a <strong>Welch’s <span class="math inline">\(t\)</span></strong> test, or an <strong>unpooled version</strong> of test.</p>
<p>A <strong>pooled version</strong> of this test exists. It has an additional assumption: that the variances of the quantitative variable is equal in the two populations (i.e. <span class="math inline">\(\sigma_X^2 = \sigma_Y^2\)</span>). The pooled version has fallen out of favor especially when the variances are unequal and when the sample sizes are unequal, as the type I error rates do not match the significance level.</p>
<div id="eg2t" class="section level3" number="14.4.1">
<h3>
<span class="header-section-number">14.4.1</span> Worked Example<a class="anchor" aria-label="anchor" href="#eg2t"><i class="fas fa-link"></i></a>
</h3>
<p>We want to assess if there is a significant difference in the average body masses of male and female Gentoo penguins.</p>
<p>From the question, we have <span class="math inline">\(H_0: \mu_f - \mu_m = 0, H_a: \mu_f - \mu_m \neq 0\)</span>.</p>
<div class="sourceCode" id="cb516"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://allisonhorst.github.io/palmerpenguins/">palmerpenguins</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">Data</span> <span class="op">&lt;-</span> <span class="fu">palmerpenguins</span><span class="fu">::</span><span class="va"><a href="https://allisonhorst.github.io/palmerpenguins/reference/penguins.html">penguins</a></span></span>
<span></span>
<span><span class="va">result_2samp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">body_mass_g</span> <span class="op">~</span> <span class="va">sex</span>, data <span class="op">=</span> <span class="va">Data</span>,</span>
<span>       subset <span class="op">=</span> <span class="va">species</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Gentoo"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">result_2samp</span></span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  body_mass_g by sex
## t = -14.761, df = 116.64, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means between group female and group male is not equal to 0
## 95 percent confidence interval:
##  -913.1130 -697.0763
## sample estimates:
## mean in group female   mean in group male 
##             4679.741             5484.836</code></pre>
<ul>
<li>The test statistic is $t = $ -14.7613684.</li>
<li>The p-value is virtually 0. So we reject the null hypothesis. The data provide evidence that the average weights of female and male Gentoo penguins are significantly different</li>
<li>The 95% confidence interval is -913.1130428, -697.0763297. Notice how this interval does not contain the value under the null hypothesis, 0. In fact, since the entire interval is below 0, we can also say that the male Gentoo penguins are heavier, on average, than their female counterparts. The conclusion is consistent with the hypothesis test.</li>
</ul>
</div>
</div>
<div id="infcomments" class="section level2" number="14.5">
<h2>
<span class="header-section-number">14.5</span> Additional Comments on Hypothesis Test of Parameters<a class="anchor" aria-label="anchor" href="#infcomments"><i class="fas fa-link"></i></a>
</h2>
<div id="inference" class="section level3" number="14.5.1">
<h3>
<span class="header-section-number">14.5.1</span> Two-Sided Tests and Confidence Intervals<a class="anchor" aria-label="anchor" href="#inference"><i class="fas fa-link"></i></a>
</h3>
<p>Notice how hypothesis tests and confidence intervals are based on the sampling distribution of the relevant estimator? If you look at how the critical value of a two-sided test and the critical value of a confidence interval are derived, you will notice that they are found in the exact same manner. Refer to Figure <a href="hyp.html#fig:9-critneq">14.5</a> and Figure <a href="CI.html#fig:8-crit">12.2</a>, and notice how these pictures look exactly the same, with the middle portion of the PDF having an area of <span class="math inline">\(1-\alpha\)</span> and the two tail ends having an area of <span class="math inline">\(\alpha\)</span>.</p>
<p>What this implies is that conclusions from a <span class="math inline">\((1-\alpha) \times 100\%\)</span> confidence interval will be consistent with a 2-sided hypothesis test conducted at significance <span class="math inline">\(\alpha\)</span>. Also notice how we use the same notation <span class="math inline">\(\alpha\)</span> for the confidence level and significance level?</p>
<ul>
<li><p>If the null hypothesis is <strong>rejected</strong> for a 2-sided test, than the value of the parameter under the null hypothesis will lie <strong>outside</strong> the corresponding confidence interval. This should make sense since the confidence interval provides a range of plausible values for the parameter and values outside the interval are considered to be “ruled out”.</p></li>
<li><p>If the null hypothesis is <strong>not rejected</strong> for a 2-sided test, than the value of the parameter under the null hypothesis will lie <strong>inside</strong> the corresponding confidence interval. This should make sense since the confidence interval provides a range of plausible values for the parameter and values outside the interval are considered to be “ruled out”.</p></li>
</ul>
<p>We noted this in the worked examples in Sections <a href="hyp.html#egpairedt">14.3.1</a> and <a href="hyp.html#eg2t">14.4.1</a>.</p>
</div>
<div id="reporting-conclusions" class="section level3" number="14.5.2">
<h3>
<span class="header-section-number">14.5.2</span> Reporting Conclusions<a class="anchor" aria-label="anchor" href="#reporting-conclusions"><i class="fas fa-link"></i></a>
</h3>
<p>You may have noticed that we make a binary decision at the end of a hypothesis test: we either reject or fail to reject a null hypothesis, by comparing our test statistic with a critical value or by comparing a p-value (which depends on the value of the test statistic) with a significance level.</p>
<p>While the decision is binary, note that the numerical value of a test statistic is not binary. We have mentioned that larger values (in magnitude) imply more evidence against the null hypothesis. Are p-values of 0.049 and 0.051 really that much different? So the p-value also can be interpreted in the same manner: smaller values imply more evidence against the null hypothesis.</p>
<p>Therefore, when writing conclusions, it is recommended to also provide the p-value or the value of the test statistic, instead of just reporting that the “null hypothesis is rejected” or “the null hypothesis is not rejected”. Readers than then make an assessment of how strong the evidence is against the null hypothesis, based on their judgement of what the value of the significance level should be.</p>

</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="boot.html"><span class="header-section-number">13</span> The Bootstrap</a></div>
<div class="next"><a href="prac.html"><span class="header-section-number">15</span> Type I and II Errors, Significance Level, Power</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#hyp"><span class="header-section-number">14</span> Hypothesis Testing for Means</a></li>
<li><a class="nav-link" href="#introduction-4"><span class="header-section-number">14.1</span> Introduction</a></li>
<li>
<a class="nav-link" href="#testmean"><span class="header-section-number">14.2</span> Hypothesis Test for the Mean</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#null-and-alternative-hypotheses"><span class="header-section-number">14.2.1</span> Null and Alternative Hypotheses</a></li>
<li><a class="nav-link" href="#test-statistic"><span class="header-section-number">14.2.2</span> Test Statistic</a></li>
<li><a class="nav-link" href="#decision"><span class="header-section-number">14.2.3</span> Making a Decision</a></li>
<li><a class="nav-link" href="#writing-conclusions"><span class="header-section-number">14.2.4</span> Writing Conclusions</a></li>
<li><a class="nav-link" href="#eg1samplet"><span class="header-section-number">14.2.5</span> Worked Example</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#hypothesis-test-for-paired-means"><span class="header-section-number">14.3</span> Hypothesis Test for Paired Means</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#egpairedt"><span class="header-section-number">14.3.1</span> Worked Example</a></li></ul>
</li>
<li>
<a class="nav-link" href="#hypothesis-test-for-difference-in-two-independent-means"><span class="header-section-number">14.4</span> Hypothesis Test for Difference in Two Independent Means</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#eg2t"><span class="header-section-number">14.4.1</span> Worked Example</a></li></ul>
</li>
<li>
<a class="nav-link" href="#infcomments"><span class="header-section-number">14.5</span> Additional Comments on Hypothesis Test of Parameters</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#inference"><span class="header-section-number">14.5.1</span> Two-Sided Tests and Confidence Intervals</a></li>
<li><a class="nav-link" href="#reporting-conclusions"><span class="header-section-number">14.5.2</span> Reporting Conclusions</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>STAT 3080: From Data to Knowledge</strong>" was written by Jeffrey Woo. It was last built on 2026-10-06.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
